name: Makefile CI

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      uses: xu-cheng/latex-action@v4
      with:
        root_file: dfg.tex
